<?php
$hairstyles = [
    [
        'name' => 'hairstyle 1',
        'image' => 'img src ="https://picsum.photos/250/100?random="',
        'description' => 'blablabla1',
        'hairlength' => 'long hair',
        'price' => '40€',
        'time' => '45min',
        'new' => true,
    ],
    [
        'name' => 'hairstyle 2',
        'image' => 'img src ="https://picsum.photos/250/100?random="',
        'description' => 'blablabla2',
        'hairlength' => 'long hair',
        'price' => '40€',
        'time' => '45min', 
        'new' => false,
    ],
    [
        'name' => 'hairstyle 3',
        'image' => 'img src ="https://picsum.photos/250/100?random="',
        'description' => 'blablabla3',
        'hairlength' => 'long hair',
        'price' => '40€',
        'time' => '45min',
        'new' => false,
    ],
    [
        'name' => 'hairstyle 4',
        'image' => 'img src ="https://picsum.photos/250/100?random="',
        'description' => 'blablabla4',
        'hairlength' => 'long hair',
        'price' => '40€',
        'time' => '45min', 
        'new' => false,
    ],
    [
        'name' => 'hairstyle 5',
        'image' => 'img src ="https://picsum.photos/250/100?random="',
        'description' => 'blablabla5',
        'hairlength' => 'long hair',
        'price' => '40€',
        'time' => '45min',
        'new' => false,
    ],
    [
        'name' => 'hairstyle 6',
        'image' => 'img src ="https://picsum.photos/250/100?random="',
        'description' => 'blablabla6',
        'hairlength' => 'long hair',
        'price' => '40€',
        'time' => '45min', 
        'new' => false,
    ],
    [
        'name' => 'hairstyle 7',
        'image' => 'img src ="https://picsum.photos/250/100?random="',
        'description' => 'blablabla7',
        'hairlength' => 'long hair',
        'price' => '40€',
        'time' => '45min',
        'new' => true,
    ],
    [
        'name' => 'hairstyle 8',
        'image' => 'img src ="https://picsum.photos/250/100?random="',
        'description' => 'blablabla8',
        'hairlength' => 'long hair',
        'price' => '40€',
        'time' => '45min', 
        'new' => false,
    ],
]
?>
